name: Databricks Asset Bundles CI

on:
  pull_request:
    branches:
      - main
      - feature/dabsdeploy
  push:
    branches:
      - main
      - feature/dabsdeploy

jobs:
  validate-and-test:
    runs-on: html_publisher

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Configure Databricks CLI authentication
        run: |
          # Set default environment to dev
          echo "DEPLOY_ENV=dev" >> $GITHUB_ENV
        env:
          DATABRICKS_HOST: 'https://e2-demo-field-eng.cloud.databricks.com'
          DATABRICKS_TOKEN: ${{ secrets.DEPLOY_NOTEBOOK_TOKEN }}

      - name: Validate bundle
        run: databricks bundle validate --var="environment=${{ env.DEPLOY_ENV }}"
        env:
          DATABRICKS_HOST: 'https://e2-demo-field-eng.cloud.databricks.com'
          DATABRICKS_TOKEN: ${{ secrets.DEPLOY_NOTEBOOK_TOKEN }}

      - name: Run and monitor workflow
        run: |
          echo "Starting workflow execution..."
          databricks bundle run demo_workflow --target dev --var="environment=${{ env.DEPLOY_ENV }}"
          echo
          echo "Workflow execution completed"
        env:
          DATABRICKS_HOST: 'https://e2-demo-field-eng.cloud.databricks.com'
          DATABRICKS_TOKEN: ${{ secrets.DEPLOY_NOTEBOOK_TOKEN }}

      - name: Cleanup PR deployment
        run: |
          databricks bundle destroy --target dev --var="environment=${{ env.DEPLOY_ENV }}" || true
        env:
          DATABRICKS_HOST: 'https://e2-demo-field-eng.cloud.databricks.com'
          DATABRICKS_TOKEN: ${{ secrets.DEPLOY_NOTEBOOK_TOKEN }}
